name: Test project

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout
        uses: actions/checkout@v3
      - name: Build 
        run: npm install -g nodemon
      - name: Run
        run: nodemon index.js
      
  
