name: Test project

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    timeout-minutes: 1000000
    steps:
      - name: Action Checkout
        uses: actions/checkout@v3
      - name: Build 
        run: npm install
      - name: Run
        run: node index.js
      
  
